Base classes for different external stimuli
FAIRmat-NFDI/nexus_definitions pull request #58
Opened 2023-08-25 12:00 UTC by lukaspie

In order to describe the chemico-physical environment of a sample during/before measurement, we want to describe external stimuli in detail. For this purpose, this is a first draft containing base classes for the following external stimuli:
- shear
- strain
- stress
- pressure
- electric field
- magnetic field
- gas environment
- thermal field

There is also a new base_class NXexternal_stimulus from which all of the other base classes inherit. So far, it is the same base class as NXenvironment, however some of the fields (such as name, short_name, description, program) and their docs describe properties of the NXsensor and should therefore be updated at some point. By having NXexternal_stimulus here already, we allow for these changes to be flexibly incorporated in the future.

2023-08-29 10:56 UTC, mkuehbach requested changes

2023-08-29 10:56 UTC, mkuehbach commented on contributed_definitions/nyaml/NXapplied_pressure.yaml
applied_pressure is a specific (often hydrostatic) applied_stress(_state) on the material, therefore replace NXapplied_pressure with NXfield_stress.

One base class named NXfield_"descriptor" for each "descriptor" like temperature, stress, strain, electric, magnetic field

2023-08-29 10:56 UTC, mkuehbach commented on contributed_definitions/nyaml/NXapplied_pressure.yaml
Personally I would add indeed an NXsensor for each base class naming these NXsensor instances with controlled words like manometer is good but also in combination with the enumeration pressure, stress, strain implicit,

I do like the idea to have a possibility for keeping measured values but what about assumed/simulated field values, this is why we might need to apply a staggered approach allowing different level of complexity:
Lemme make an example for stress:

Some people wish to collect an assumed stress value (this can be a pressure) and can be a scalar
but when it is a scalar it is typically either a projected or averaged value, e.g. "von Mises equivalent stress" the actual field quantities are a tensor
thus we should have the possibility to write down tensors
e.g. a stress tensor etc. 
This is continuum physics, now there are different notations for such tensor, e.g. the full tensor of elastic constants, or the reduced Voigt-Reuss notation or the familiar 3x3 stress tensor or as mentioned above a single scalar.

In most cases we cannot measure the full tensorial information using a single NXsensor if at all with a sensor.
The stress is typically computed from input from such sensors (e.g. time-displacement)

Maybe it is indeed good to just add a notation of an (NXsensor) in the base class maybe with some instance name suggestions in its docstring. In addition then one field for a scalar value like e.g. cauchy_stress and one field for the full tensor etc.

2023-08-29 10:56 UTC, mkuehbach commented on contributed_definitions/nyaml/NXapplied_pressure.yaml
Again just that all this is possible does not need to mean it has to be used when creating/using an instance of that base class.

2023-08-29 10:56 UTC, mkuehbach commented on contributed_definitions/nyaml/NXapplied_pressure.yaml
> +      Applied pressure. Could a a single float value for static field or
I would rather think about a (nx, ny, nz, 3, 3) field for e.g. a field quantity with a tensor at each point, these are typical pieces of information collected e.g. in the AddMorePower project

2023-08-29 10:56 UTC, mkuehbach commented on contributed_definitions/nyaml/NXapplied_pressure.yaml
> +NXapplied_pressure(NXexternal_stimulus):
I am convinced having a "depends_on" field for the quantity is useful to specify in which reference frame the quantity is defined. The main need for having something like this is that in continuum mechanics you often tend to distinguish different reference configurations, i.e. frames of references (the deformed the undeformed) coordinate system and being specific in which coordinate system the quantity is defined is vital in such applications. With NeXus and NXcoordinate_system(_set) plus NXtransformations we have all this at our fingertips which is much more powerful than plain ad hoc generated flat lists of key-value pairs like e.g. also used in NOMAD metainfo right now

2023-08-29 10:56 UTC, mkuehbach commented on contributed_definitions/nyaml/NXapplied_shear.yaml
NXfield_deformation or NXfield_distortion

2023-08-29 10:56 UTC, mkuehbach commented on contributed_definitions/nyaml/NXapplied_strain.yaml
shear is a special strain along a specific coordinate direction this is why I am convinced we do need only NXfield_stress, NXfield_strain or NXfield_distortion but not pressure, stress, shear, strain

2023-08-29 10:56 UTC, mkuehbach commented on contributed_definitions/nyaml/NXexternal_stimulus.yaml
I am not completely sure whether the above-suggested NXfield_"descriptor" base class should compose from NXexternal_stimulus or whether an instance of NXexternal_stimulus should just use them as base classes:

e.g.

NXexternal_stimulus:
\t(NXfield_stress)

2023-08-29 10:56 UTC, mkuehbach commented on contributed_definitions/nyaml/NXexternal_stimulus.yaml
> +  type:
would it make sense to move these fields to NXfabrication and then just hook in an instance of NXfabrication

2023-08-29 10:56 UTC, mkuehbach commented on contributed_definitions/nyaml/NXexternal_stimulus.yaml
> +  depends_on(NX_CHAR):
in which coordinate system

2023-08-29 10:56 UTC, mkuehbach commented on contributed_definitions/nyaml/NXgas_environment.yaml
> +  gases(NX_CHAR):
instances of NXion or InChi or other standard names but not free text names

2023-08-29 10:56 UTC, mkuehbach commented on contributed_definitions/nyaml/NXgas_environment.yaml
> +    unit: NX_UNITLESS
no, a concentration is 1/AREA or 1/VOLUME so the unit is NX_ANY until we have no better way to write out unit categories in NeXus directly

2023-08-29 10:56 UTC, mkuehbach commented on contributed_definitions/nyaml/NXgas_environment.yaml
> +  pressure(NX_FLOAT):
partial_pressure? how measured?

2023-08-29 10:56 UTC, mkuehbach commented on contributed_definitions/nyaml/NXmagnetic_field.yaml
shouldn't we combine this with electric field
into a base class
NXfield_electromagnetic

2023-08-29 10:56 UTC, mkuehbach commented on contributed_definitions/nyaml/NXthermal_field.yaml
how to handle the case of a collection of descriptor value over time
one field "time" and another field with as many values as for "time" but this other field named "temperature"?

2023-08-29 10:56 UTC, mkuehbach commented on contributed_definitions/nyaml/NXgas_environment.yaml
In how far should we document the stability of this environment, I suggest to also add a geometry with which if needed to describe the environment

2024-06-04 09:07 UTC, lukaspie commented
Closed since we now have the NXactuator/NXsensor structure within NXenvironment.

2024-06-04 09:07 UTC, closed without merging