Remove sample history from MPES
FAIRmat-NFDI/nexus_definitions pull request #82
Opened 2023-10-24 07:53 UTC by lukaspie

It was discussed in our MPES meetings on [instrument history](https://github.com/FAIRmat-NFDI/data-modeling/blob/main/mpes/meetings/2023-10-18_calibration_instrument-history_legacy-data.md), that we don't want ro use NeXus to describe the complete history of the instrument and the sample, since this should be done on the level of the research data management system. We said "we consider a nexus file as a snapshot of an experimental setup, so it should not contain all possible histories but it may contain links/references to these histories (e.g., in nomad)."

If we are being strict, that also means that the sample history (and potentially even prior NXcalibration events) should not be part of the NeXus file. This PR is meant as a place to discuss if we want to keep these histories. To me, there are three options:
1) Remove all notion of sample/instrument history -> shall be figured out by RDM system somewhere else
2) Keep some descriptors of sample and instrument history -> this can be NXsample_history as well as NXcalibration events on the instrument (prior to experiment)
3) Allow for an even more detailed description of the history of all relevant experimental items, e.g. attach a NXhistory (comprised of NXactivities) to each entity. In this case, the local RDM system could even populate the NeXus file with the stored history (or links to it).

@FAIRmat-NFDI/areab

2023-11-01 11:30 UTC, mkuehbach requested changes
See the first comment

2023-11-01 11:30 UTC, mkuehbach commented on base_classes/NXsample.nxdl.xml
Thanks @lukaspie for indeed summarizing the options we have:
There is a fundamental point to consider which very often implicitly goes together in the research practice but which conceptually combines different points:
For all tracking of provenance (whether temporal or logically) we need to have clear identifier to states of objects.
Now what is the sample id the sample id is practically a hash/name given to the sample to which one refers to when that same piece of material is carried through a sequence/workflow of analysis steps (in one instrument or in n instruments) does not matter. However, physically all instruments induce a change of the state of the sample (in some steps and cases significant and worth to be mentioned in many cases just ignore or considered irrelevant) so far so good. 

The point is if we drop sample_history completely we are if at all given a sample_id plus maybe a ISO8601 date + local offset to contextualize that NeXus artifact on the time axis and the provenance path.
How do we know that the same sample_id was used throughout ALL analyses performed on this measurement?
Usually we do not know this but we much more often just assume this (and admittedly that is a practical assumption and often a good choice). Fact though is that is an assumption we know as researchers that we should communicate to the RDMS. But now take a process where you cut a specimen B from the sample A or every other case where you have a junction on the provenance graph. Say we have a big chunk of material named A and cut a specimen from it named B.
What we want in the RDMS or elsewhere but at least somewhere is that we have some place which tells 
B was generated from A. Now say sample_history is this place to store A (in the NeXus instance) if the NeXus instance talks about the experiment done on specimen B. If we drop that how do we gonna bookkeep that connection between A and B?

The original reason why I introduced that sample_history 1,5 years ago is to have this breadcrumb. Indeed, the name "history" might imply a connotation that is worth to be reconsidered and renamed if it is not misleading but the point remains justified: The NeXus instance stores a hint where you are coming from, like the input of a computer simulation as a parameter to a computer simulation.

I agree that the actual provenance graph is what - if I would have a group - I do expect to be the RDMS's job to do right. Therefore, yes we can drop sample_history and the idea that is behind it but then we need to talk much more specific and give much more specific guidance as to what is the sample_id.

Area A to my understanding in most cases argues that they follow a physical sample non-destructively through its journey through different instruments whereby that sample is getting characterized. All good and justified. In this case having no breadcrumb like sample_history would work because the research knows that when he types the sample_id B we will get all nodes on the graph where that sample_id B appears and with timestamps one would have immediately the history.

BUT that is just one use case that NOMAD OASIS has to deal with: in the case of atom probe and actually all cases where you cut sample into n this approach falls short as the specimen B is always cut from A and when thus there is no hint where to note this origin/provenance/history there is no chance for the RDMS to contextualize unless assuming that same sample_ids having something to do with one another but exactly that assumption is wrong because A is not B neither physically nor is there a non-significant difference between the state and properties of A and B.

Therefore, my proposal is three-fold:
1. Make at least one time breadcrumb in a NeXus instance required: ISO8601 + local offset to UTC, e.g. start_time
2. Make a field alike sample_id in NXsample required but other sample alias can be optional so that there is always one absolutely clear identifier, I am still convinced nomad should offer to have a sample registry anyway...
3. leave a place for the breadcrumb how that specific sample_id links to another sample_id or explicitly state that the link is "None" such as the sample was produced with no relevant history what we want to keep track of (for whatever reasons this oftentimes is practically the typical situation). Thart link should always be required and stored in NeXus OR (i.e. if we gonna drop sample_history) we have to design
   another documentation mechanism whereby this information can be passed to the RDMS (i.e. NOMAD OASIS) in another way, e.g. ELN but then why not have it in the NeXus instance in the first place? The specific case of area A where always the same physical sample is carried through is for substantiated reason an inacceptable simplification irrespective that it works admittedly for many cases namely when you assume you have no junctions on the provenance graph but its always the same sample.

2023-11-01 11:30 UTC, mkuehbach commented on contributed_definitions/NXactivity.nxdl.xml
What is the reason that NXactivity and NXchemical process were removed?

2023-11-01 11:32 UTC, mkuehbach commented on base_classes/NXsample.nxdl.xml
I am not sure whether the specific workflow of sample provenance in mpes is more alike the model in Area A in this case, sure sample_history can be removed but for MPES, for NXem and NXapm I argue for substantiated reasons to leave a place where one can store at least one piece of information from where the sample came and that must not be done using a free text field

2023-11-01 11:37 UTC, mkuehbach commented on base_classes/NXsample.nxdl.xml
or sample_link plus a clear docstring an indeed the original docstring of "sample_history"
"A set of physical processes that occurred to the sample prior/during experiment" is then poor instead
"Identifier of the sample from which the sample was cut or the string "None" . The purpose of this field is to support functionalities for tracking sample provenance in e.g. a research data management system.

2023-11-02 15:16 UTC, lukaspie commented on contributed_definitions/NXactivity.nxdl.xml
If we are not planning to track anything other than actual measurements in NXentries, I don't see the reason to track activities or chemical/physical processes on the sample with NeXuS. These classes until now only existed to describe the sample history.

2023-11-02 15:17 UTC, lukaspie commented on base_classes/NXsample.nxdl.xml
Alternatively, linking to one or more separate samples (by sample_link or sample_parent) may be a good compromise.

2023-11-02 16:03 UTC, mkuehbach commented on base_classes/NXsample.nxdl.xml
I am using parent_identifier(NX_CHAR) now in NXem:
doc:
          Identifier of the sample from which the sample was cut or the string
          *None*. The purpose of this field is to support functionalities
          for tracking sample provenance via a research data management system.

2023-11-02 16:14 UTC, lukaspie commented on base_classes/NXsample.nxdl.xml
But what if I have multiple parents? For example, I mix together two samples that I synthesized previously, then I add another chemical, and then I take a smaller piece of this batch for the measurement? What do I write into `parent_identifier(NX_CHAR)`. My point is that this gets quite complicated and should be done by a proper RDM system and not in the NeXuS file. Sure, we can have this field here to at least give an indication, but it may also be confusing in this more complex case.

2023-11-23 09:44 UTC, rettigl commented
> It was discussed in our MPES meetings on [instrument history](https://github.com/FAIRmat-NFDI/data-modeling/blob/main/mpes/meetings/2023-10-18_calibration_instrument-history_legacy-data.md), that we don't want to use NeXus to describe the complete history of the instrument and the sample, since this should be done on the level of the research data management system. We said "we consider a nexus file as a snapshot of an experimental setup, so it should not contain all possible histories but it may contain links/references to these histories (e.g., in nomad)."
> 
> If we are being strict, that also means that the sample history (and potentially even prior NXcalibration events) should not be part of the NeXus file. This PR is meant as a place to discuss if we want to keep these histories. To me, there are three options:
> 
>     1. Remove all notion of sample/instrument history -> shall be figured out by RDM system somewhere else
> 
>     2. Keep some descriptors of sample and instrument history -> this can be NXsample_history as well as NXcalibration events on the instrument (prior to experiment)
> 
>     3. Allow for an even more detailed description of the history of all relevant experimental items, e.g. attach a NXhistory (comprised of NXactivities) to each entity. In this case, the local RDM system could even populate the NeXus file with the stored history (or links to it).

I might have missed that discussion. It might be a good idea to not require such history to be part of a nexus file, but we should make sure that we do not make our files depending on a specific environment: They should be understandable on their own, and if we link to anything else, then this needs to be accessible and have a DOI etc. 

I would suggest to keep at least the possibility to put some rudimentary documentation of how the sample was handled and where it derived from in the file as an option, because this makes the file mode interoperable, I would argue.

2024-01-05 13:32 UTC, lukaspie commented
I am closing this PR since in the meantime we have agreed to keep `NXsample_history` as it is right now. This is the only way to keep more information about the sample preparation in MPES together with the data in the same entry. We agreed that once a better description of the sample pronvenance is possible (i.e., by RDM systems), we can review  `NXsample_history` and `NXactivity` and possibly replace them by links to these RDM descriptions.

2024-01-05 13:32 UTC, closed without merging